# Project information
site_name: Windows 365
site_url: https://stealthpuppy.com/w365
site_author: Aaron Parker
site_description: >-
  Build a quick and dirty image for Windows 365

# Repository
repo_name: "" #aaronparker/packer
repo_url: "" #https://github.com/aaronparker/packer
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 Aaron Parker

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.instant
    #- navigation.top
    #- navigation.tabs
    - navigation.expand
  palette:
    - scheme: default
      primary: purple
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  #icon:
    #logo: logo
  logo: assets/images/start.png

  # Table sort
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  #- javascripts/tables.js

# Plugins
plugins:
  #- search
  - redirects:
      redirect_maps:
  - minify:
      minify_html: true
      minify_js: true

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aaronparker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/stealthpuppy
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aaronedwardparker/
  generator: false

nav:
  - Home: index.md